'use strict';

module.exports = {
  CREATE_SCENE: 'CREATE_SCENE',
  PRIMITIVE_ADD_MARK: 'PRIMITIVE_ADD_MARK',
  PRIMITIVE_SET_PARENT: 'PRIMITIVE_SET_PARENT',
  VEGA_INVALIDATE: 'VEGA_INVALIDATE',
  VEGA_PARSE: 'VEGA_PARSE',
  INIT_SIGNAL: 'INIT_SIGNAL',
  SET_SIGNAL: 'SET_SIGNAL',
  SET_SIGNAL_STREAMS: 'SET_SIGNAL_STREAMS',
  UNSET_SIGNAL: 'UNSET_SIGNAL',
  PIPELINE_SELECT: 'PIPELINE_SELECT',
  EXPAND_LAYERS: 'EXPAND_LAYERS',
  REMOVE_LAYERS: 'REMOVE_LAYERS',
  SELECT_MARK: 'SELECT_MARK',
  TOGGLE_LAYERS: 'TOGGLE_LAYERS'
};

Object.freeze(module.exports);
