'use strict';

module.exports = {
  CREATE_SCENE: 'CREATE_SCENE',
  HINTS_CLEAR: 'HINTS_CLEAR',
  HINTS_ON: 'HINTS_ON',
  HINTS_DISPLAY: 'HINTS_DISPLAY',
  MARK_ADD: 'MARK_ADD',
  MARK_DELETE: 'MARK_DELETE',
  MARK_SET_PARENT: 'MARK_SET_PARENT',
  MARK_UPDATE_PROPERTY: 'MARK_UPDATE_PROPERTY',
  VEGA_INVALIDATE: 'VEGA_INVALIDATE',
  VEGA_PARSE: 'VEGA_PARSE',
  SIGNAL_INIT: 'SIGNAL_INIT',
  SIGNAL_SET: 'SIGNAL_SET',
  SIGNAL_SET_STREAMS: 'SIGNAL_SET_STREAMS',
  SIGNAL_UNSET: 'SIGNAL_UNSET',
  RULES_ADD_SCALE_TO_GROUP: 'RULES_ADD_SCALE_TO_GROUP',
  RULES_ADD_LEGEND_TO_GROUP: 'RULES_ADD_LEGEND_TO_GROUP',
  RULES_ADD_AXIS_TO_GROUP: 'RULES_ADD_AXIS_TO_GROUP',
  RULES_SET_PROPERTY: 'RULES_SET_PROPERTY',
  RULES_DISABLE_PROPERTY: 'RULES_DISABLE_PROPERTY',
  RULES_RESET_PROPERTY: 'RULES_RESET_PROPERTY',
  PIPELINE_SELECT: 'PIPELINE_SELECT',
  CREATE_PIPELINE: 'CREATE_PIPELINE',
  UPDATE_PIPELINE_DATASET: 'UPDATE_PIPELINE_DATASET',
  EXPAND_LAYERS: 'EXPAND_LAYERS',
  REMOVE_LAYERS: 'REMOVE_LAYERS',
  SELECT_MARK: 'SELECT_MARK',
  TOGGLE_LAYERS: 'TOGGLE_LAYERS',
  SET_ACTIVE_WALKTHROUGH: 'SET_ACTIVE_WALKTHROUGH',
  SET_ACTIVE_STEP: 'SET_ACTIVE_STEP',
  SET_WALKTHROUGH: 'SET_WALKTHROUGH',
  SET_WALKTHROUGH_ON: 'SET_WALKTHROUGH_ON'
};

Object.freeze(module.exports);
