'use strict';

module.exports = {
  'group-open': require('../../assets/mark-group-open.svg'),
  'group-closed': require('../../assets/mark-group-closed.svg'),
  rect: require('../../assets/mark-rect.svg'),
  line: require('../../assets/mark-line.svg'),
  area: require('../../assets/mark-area.svg'),
  text: require('../../assets/mark-text.svg'),
  symbol: require('../../assets/mark-symbol.svg'),
  trash: require('../../assets/trash.svg'),
  plus: require('../../assets/plus.svg'),
  undo: require('../../assets/undo.svg'),
  redo: require('../../assets/redo.svg'),
  database: require('../../assets/database.svg'),
  nominal: require('../../assets/type-nominal.svg'),
  ordinal: require('../../assets/type-ordinal.svg'),
  quantitative: require('../../assets/type-quantitative.svg'),
  temporal: require('../../assets/type-temporal.svg'),
  prev: require('../../assets/prev.svg'),
  next: require('../../assets/next.svg'),
  close: require('../../assets/close.svg'),
  hamburger: require('../../assets/hamburger.svg'),
  erase: require('../../assets/erase.svg'),
  export: require('../../assets/export.svg'),
  scaffold: require('../../assets/scaffold.html'),
  sort: require('../../assets/sort.svg'),
  sortAlphaAsc: require('../../assets/sort-alpha-asc.svg'),
  sortAlphaDesc: require('../../assets/sort-alpha-desc.svg'),
  sortNumericAsc: require('../../assets/sort-numeric-asc.svg'),
  sortNumericDesc: require('../../assets/sort-numeric-desc.svg'),
  filter: require('../../assets/filter.svg')
};
